version: '3.8'

services:
  app:
    build: .
    command: yarn dev
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/src
      - node_modules-volume:/src/node_modules

volumes:
  node_modules-volume:
